apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uni-pvc
  namespace: uni-ns
spec:
  storageClassName: fitness-sc
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi