apiVersion: apps/v1 
kind: StatefulSet
metadata:
  name: mariadb
  namespace: uni-ns
spec:
  replicas: 3
  minReadySeconds: 10
  serviceName: mariadb
  selector:
    matchLabels:
      app: mariadb 
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mariadb-container
        image: mariadb:11
        ports:
        - containerPort: 3306
        envFrom:
        - configMapRef:
            name: uni-config
        volumeMounts:
        - name: mariadb-storage
          mountPath: /var/lib/mysql
        
        - name: mariadb-init
          mountPath: /docker-entrypoint-initdb.d
      volumes:

      - name: mariadb-init
        configMap:
          name: mariadb-init-script
  volumeClaimTemplates:
  - metadata:
      name: mariadb-storage
    spec:
      storageClassName: fitness-sc
      accessModes:
      - ReadWriteMany
      resources:
        requests:
          storage: 2Gi